const JobEventEmitterEnums = Object.freeze({
    REQUEST_ALL_JOBS_TO_CANCEL: "REQUEST_ALL_JOBS_TO_CANCEL",
    IMAGE_DATA_TO_UPLOAD: "IMAGE_DATA_TO_UPLOAD",
    IMAGE_URL_TO_DOWNLOAD: "IMAGE_URL_TO_DOWNLOAD",
    ADD_DOM_TEXT: "ADD_DOM_TEXT",
    ADD_URL_TO_PROCESS: "ADD_URL_TO_PROCESS",
    ADD_IMAGE_BUFFER: "ADD_IMAGE_BUFFER",
});

module.exports = { JobEventEmitterEnums };
