pipeline {
    agent any

    tools {
        nodejs 'NodeJS 20'
    }

    environment {
        GITHUB_REPO = 'https://github.com/wee-zard/eu-lucas-project.git'
        BRANCH = 'main'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: env.BRANCH, url: env.GITHUB_REPO
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install --legacy-peer-deps'
            }
        }

        stage('Check types') {
            steps {
                sh 'npm run check-types'
            }
        }

        stage('Test Source') {
            steps {
                sh 'npm run test'
            }
        }

        stage('Build') {
            steps {
                sh 'craco build'
            }
        }

        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: 'dist/**/*', fingerprint: true
            }
        }

        stage('Deploy') {
            when {
                anyOf {
                    branch env.BRANCH
                }
            }
            steps {
                echo 'TODO: Deploying the application'
            }
        }

        stage('Clean') {
            steps {
                deleteDir()
            }
        }
    }

    post {
        success {
            echo 'Pipeline run successfully.'
        }
        failure {
            echo 'Pipeline failed to run.'
        }
    }
}