export enum BackgroundConsts {
  SET_BACKGROUND_BACKDROP_OPEN = "SET_BACKGROUND_BACKDROP_OPEN",
  SET_BACKGROUND_BACKDROP_CONFIG = "SET_BACKGROUND_BACKDROP_CONFIG",
  SET_BACKGROUND_CANVAS_IMAGE_PROPERTIES = "SET_BACKGROUND_CANVAS_IMAGE_PROPERTIES",
  SET_BACKGROUND_CANVAS_DATA_URL = "SET_BACKGROUND_CANVAS_DATA_URL",
}
