export enum BoundingBoxConsts {
  SET_BOUNDING_BOX_DIALOG_OPEN = "SET_BOUNDING_BOX_DIALOG_OPEN",
  SET_BOUNDING_BOX_COLORS = "SET_BOUNDING_BOX_COLORS",
  SET_BOUNDING_BOX_PERCENTAGE_DISPLAY = "SET_BOUNDING_BOX_PERCENTAGE_DISPLAY",
}
