export enum ConfirmationDialogConsts {
  SET_CONFIRMATION_DIALOG_OPEN = "SET_CONFIRMATION_DIALOG_OPEN",
  SET_CONFIRMATION_DIALOG_CONFIG = "SET_CONFIRMATION_DIALOG_CONFIG",
  SET_CONFIRMATION_DIALOG_SUBMIT_CLICKED = "SET_CONFIRMATION_DIALOG_SUBMIT_CLICKED",
  SET_CONFIRMATION_DIALOG_CANCEL_CLICKED = "SET_CONFIRMATION_DIALOG_CANCEL_CLICKED",
  SET_CONFIRMATION_DIALOG_RESET = "SET_CONFIRMATION_DIALOG_RESET",
}
