export enum CoordinateYConsts {
  REQUEST_COORDINATE_Y = "REQUEST_COORDINATE_Y",
  REQUESTING_COORDINATE_Y_FAILED = "REQUESTING_COORDINATE_Y_FAILED",
  REQUESTING_COORDINATE_Y_SUCCEEDED = "REQUESTING_COORDINATE_Y_SUCCEEDED",
}
