export enum CoordinateXConsts {
    REQUEST_COORDINATE_X = "REQUEST_COORDINATE_X",
    REQUESTING_COORDINATE_X_FAILED = "REQUESTING_COORDINATE_X_FAILED",
    REQUESTING_COORDINATE_X_SUCCEEDED = "REQUESTING_COORDINATE_X_SUCCEEDED",
}