export enum CoordinateYConsts {
    REQUEST_COORDINATE_Y = "REQUEST_COORDINATE_Y",
    REQUESTING_COORDINATE_Y_FAILED = "REQUESTING_COORDINATE_Y_FAILED",
    REQUESTING_COORDINATE_Y_SUCCEDED = "REQUESTING_COORDINATE_Y_SUCCEDED",
}