export enum CreationCountryConsts {
    REQUEST_CREATION_COUNTRY = "REQUEST_CREATION_COUNTRY",
    CREATION_COUNTRY_FAILED = "CREATION_COUNTRY_FAILED",
    CREATION_COUNTRY_SUCCEDED = "CREATION_COUNTRY_SUCCEDED",
}