export enum CreationDirectionConsts {
  REQUEST_CREATION_DIRECTION = "REQUEST_CREATION_DIRECTION",
  CREATION_DIRECTION_FAILED = "CREATION_DIRECTION_FAILED",
  CREATION_DIRECTION_SUCCEEDED = "CREATION_DIRECTION_SUCCEEDED",
}
