export enum CreationCountryConsts {
  REQUEST_CREATION_COUNTRY = "REQUEST_CREATION_COUNTRY",
  CREATION_COUNTRY_FAILED = "CREATION_COUNTRY_FAILED",
  CREATION_COUNTRY_SUCCEEDED = "CREATION_COUNTRY_SUCCEEDED",
}
