export enum ExifKeyConsts {
    REQUEST_EXIF_KEY = "REQUEST_EXIF_KEY",
    REQUESTING_EXIF_KEY_FAILED = "REQUESTING_EXIF_KEY_FAILED",
    REQUESTING_EXIF_KEY_SUCCEDED = "REQUESTING_EXIF_KEY_SUCCEDED",
}