export enum FolderSelectionConsts {
  SET_FOLDER_SELECTION_DIALOG_OPEN = "SET_FOLDER_SELECTION_DIALOG_OPEN",
  SET_FOLDER_SELECTION_DIALOG_EDITING_FOLDER = "SET_FOLDER_SELECTION_DIALOG_EDITING_FOLDER",
  SET_FOLDER_SELECTION_DIALOG_RESPONSE = "SET_FOLDER_SELECTION_DIALOG_RESPONSE",
  SET_FOLDER_SELECTION_DIALOG_MENU_ACTION = "SET_FOLDER_SELECTION_DIALOG_MENU_ACTION",
}
