export enum FolderConsts {
  SET_SELECTED_FOLDER_SETTING_CELL_OPTION = "SET_SELECTED_FOLDER_SETTING_CELL_OPTION",
  SET_FOLDER_CREATION_DIALOG_OPEN = "SET_FOLDER_CREATION_DIALOG_OPEN",
  SET_IMAGE_TO_FOLDER_ADDITION_DIALOG_OPEN = "SET_IMAGE_TO_FOLDER_ADDITION_DIALOG_OPEN",
}
