export enum FolderCreationConsts {
  SET_FOLDER_CREATION_DIALOG_OPEN = "SET_FOLDER_CREATION_DIALOG_OPEN",
  SET_FOLDER_CREATION_DIALOG_EMPTY_FOLDER_CREATED = "SET_FOLDER_CREATION_DIALOG_EMPTY_FOLDER_CREATED",
  SET_FOLDER_CREATION_DIALOG_EDITING_FOLDER = "SET_FOLDER_CREATION_DIALOG_EDITING_FOLDER",
}
