export enum ImageConsts {
  SET_SELECTED_IMAGES_MODEL = "SET_SELECTED_IMAGES_MODEL",
  SET_QUERIED_IMAGE_MODEL = "SET_QUERIED_IMAGE_MODEL",
  SET_SELECTED_IMAGE = "SET_SELECTED_IMAGE",
  SET_FILTER_MENU_ACTION = "SET_FILTER_MENU_ACTION",
  SET_FILTERING_PAGEABLE_PROPERTIES = "SET_FILTERING_PAGEABLE_PROPERTIES",
  SET_FILTERING_PAGEABLE_RESPONSE = "SET_FILTERING_PAGEABLE_RESPONSE",
}
