export enum ImageConsts {
    SET_SELECTED_IMAGES = "SET_SELECTED_IMAGES",
    SET_SELECTED_FILTER_TAB = "SET_SELECTED_FILTER_TAB",
    SET_IMAGE_FILTERING_FORM = "SET_IMAGE_FILTERING_FORM",
    SET_FILTER_FORM_DATA_GRID = "SET_FILTER_FORM_DATA_GRID",
    SET_FILTER_MENU_ACTION = "SET_FILTER_MENU_ACTION",
    SET_QUERY_BUILDER_MODEL = "SET_QUERY_BUILDER_MODEL",
}