export enum PlantSpeciesConsts {
  REQUEST_PLANT_SPECIES = "REQUEST_PLANT_SPECIES",
  REQUESTING_PLANT_SPECIES_FAILED = "REQUESTING_PLANT_SPECIES_FAILED",
  REQUESTING_PLANT_SPECIES_SUCCEEDED = "REQUESTING_PLANT_SPECIES_SUCCEEDED",
}
