export enum ProcedureConsts {
  REQUEST_PROCEDURE = "REQUEST_PROCEDURE",
  REQUESTING_PROCEDURE_FAILED = "REQUESTING_PROCEDURE_FAILED",
  REQUESTING_PROCEDURE_SUCCEEDED = "REQUESTING_PROCEDURE_SUCCEEDED",
}
