export enum ProcedureLogParamConsts {
  REQUEST_PROCEDURE_LOG_PARAM = "REQUEST_PROCEDURE_LOG_PARAM",
  REQUESTING_PROCEDURE_LOG_PARAM_FAILED = "REQUESTING_PROCEDURE_LOG_PARAM_FAILED",
  REQUESTING_PROCEDURE_LOG_PARAM_SUCCEEDED = "REQUESTING_PROCEDURE_LOG_PARAM_SUCCEEDED",
}
