export enum ProcedureLogConsts {
  SET_PROCEDURE_LOG_SELECTED_LOGS = "SET_PROCEDURE_LOG_SELECTED_LOGS",
  SET_PROCEDURE_LOG_PAGEABLE_PROPERTIEs = "SET_PROCEDURE_LOG_PAGEABLE_PROPERTIEs",
  SET_PROCEDURE_LOG_STORAGE_TO_DEFAULT = "SET_PROCEDURE_LOG_STORAGE_TO_DEFAULT",
  SET_PROCEDURE_LOG_SETTING_CELL = "SET_PROCEDURE_LOG_SETTING_CELL",
}
