export enum ProcedureLogConsts {
  SET_PROCEDURE_LOGS = "SET_PROCEDURE_LOGS",
  SET_PROCEDURE_LOG_SELECTED_LOGS = "SET_PROCEDURE_LOG_SELECTED_LOGS",
  SET_PROCEDURE_LOG_PAGEABLE_PROPERTIEs = "SET_PROCEDURE_LOG_PAGEABLE_PROPERTIEs",
}
