apiVersion: skaffold/v3
kind: Config
metadata:
  name: lucas-app

build:
  artifacts:
  - image: backend-image
    context: backend
    docker:
      dockerfile: Dockerfile-backend
      buildArgs:
        JAR_FILE: "spring-boot-0.2.0.jar"

  - image: my-nginx
    context: nginx
    docker:
      dockerfile: Dockerfile-nginx-ssl
    # TODO: Uncomment when there are actual HTML files inside the nginx/html folder.
    #sync:
    #  # Auto-sync changes for faster development
    #  manual:
    #    - src: "nginx/html/**"
    #      dest: "/usr/share/nginx/html"
  local:
    push: false
    useDockerCLI: true
    useBuildkit: false

manifests:
  rawYaml:
    - k8s/mysql-deployment.yaml
    - k8s/backend-deployment.yaml
    - k8s/certbot-pvc.yaml          # PVC first
    - k8s/nginx-deployment.yaml     # Then nginx (it also uses PVC)
    #- k8s/certbot-initial.yaml    # Don't include this in skaffold - run manually
    - k8s/ingress.yaml

portForward:
  - resourceType: service
    resourceName: nginx-service
    port: 80
    localPort: 8080
deploy:
  kubectl: {}