apiVersion: skaffold/v3
kind: Config
metadata:
  name: lucas-app

build:
  artifacts:
  - image: backend-image
    context: backend
    docker:
      dockerfile: Dockerfile-backend
      buildArgs:
        JAR_FILE: "spring-boot-0.2.0.jar"

  - image: my-nginx
    context: nginx
    docker:
      dockerfile: Dockerfile-nginx-ssl
  local:
    push: false
    useDockerCLI: true
    useBuildkit: false

manifests:
  rawYaml:
    - k8s/mysql-deployment.yaml
    - k8s/backend-deployment.yaml
    - k8s/certbot-pvc.yaml
    - k8/webroot-pvc.yaml
    - k8/pvc-debug.yaml
    - k8s/nginx-deployment.yaml
    - k8s/certbot-initial.yaml
    - k8s/ingress.yaml

portForward:
  - resourceType: service
    resourceName: nginx-service
    port: 80
    localPort: 8080
deploy:
  kubectl: {}