export enum SnackEnum {
  LOG_NOT_FOUND = "screens.bounding-box.notifications.log-not-found",
  CANNOT_SELECT_MORE_LOGS = "screens.bounding-box.notifications.cannot-select-more-logs",
  REFRESH_TOKEN_IS_MISSING = "guards.authentication.refresh-token-is-missing",
  ACCESS_TOKEN_IS_MISSING = "guards.authentication.access-token-is-missing",
  REPORT_SENT_OUT = "screens.reporting.notifications.report-sent-out",
  REPORT_NOT_SENT_OUT = "screens.reporting.notifications.report-cannot-be-sent-out",
  ERROR_ON_LOGIN = "screens.login.notifications.error-on-login",
  UPLOADED_XML_FILES = "screens.upload-procedures.notifications.successful-file-upload",
  FOLDER_IS_CREATED = "screens.folders.notifications.folder-is-created",
  FOLDER_IS_UPDATED = "screens.folders.notifications.folderIsUpdated",
  IMAGES_TO_FOLDER = "screens.folders.notifications.images-added-to-folder",
  NO_IMAGE_TO_ADD_TO_FOLDER = "screens.folders.notifications.no-image-to-add-to-folder",
  FOLDER_IS_DELETED = "notifications.success.folderIsDeleted",
  LOG_IS_DELETED = "notifications.success.logIsDeleted",
  FOLDER_IS_CLEARED = "notifications.success.folderIsCleared",
  IMAGE_SERVER_IS_TURNED_ON = "screens.settings.imageServerIsTurnedOn",
  IMAGE_SERVER_IS_TURNED_ON_BUT_NOT_FOUND = "screens.settings.imageServerIsTurnedOnButNotFound",
  ERROR_WHILE_DOWNLOADING_ZIP = "helpers.zip.errorWhileDownloadingZip",
  ZIP_DOWNLOADED = "helpers.zip.zipDownloaded",
  UPLOADED_ERROR_NOTIFICATION = "screens.upload-procedure.error.uploadedErrorNotification",
  ZIP_IMAGE_SERVER_ERROR = "helpers.zip.ImageServerError",
}
